/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_HWIL_PB_H_INCLUDED
#define PB_HWIL_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _HWIL { 
    bool has_gyroX;
    float gyroX;
    bool has_gyroY;
    float gyroY;
    bool has_gyroZ;
    float gyroZ;
    bool has_accX;
    float accX;
    bool has_accY;
    float accY;
    bool has_accZ;
    float accZ;
    bool has_relativeAlt;
    float relativeAlt;
    bool has_latitude;
    float latitude;
    bool has_longitude;
    float longitude;
    pb_callback_t pwm;
} HWIL;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HWIL_init_default                        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define HWIL_init_zero                           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HWIL_gyroX_tag                           1
#define HWIL_gyroY_tag                           2
#define HWIL_gyroZ_tag                           3
#define HWIL_accX_tag                            4
#define HWIL_accY_tag                            5
#define HWIL_accZ_tag                            6
#define HWIL_relativeAlt_tag                     7
#define HWIL_latitude_tag                        8
#define HWIL_longitude_tag                       9
#define HWIL_pwm_tag                             10

/* Struct field encoding specification for nanopb */
#define HWIL_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    gyroX,             1) \
X(a, STATIC,   OPTIONAL, FLOAT,    gyroY,             2) \
X(a, STATIC,   OPTIONAL, FLOAT,    gyroZ,             3) \
X(a, STATIC,   OPTIONAL, FLOAT,    accX,              4) \
X(a, STATIC,   OPTIONAL, FLOAT,    accY,              5) \
X(a, STATIC,   OPTIONAL, FLOAT,    accZ,              6) \
X(a, STATIC,   OPTIONAL, FLOAT,    relativeAlt,       7) \
X(a, STATIC,   OPTIONAL, FLOAT,    latitude,          8) \
X(a, STATIC,   OPTIONAL, FLOAT,    longitude,         9) \
X(a, CALLBACK, REPEATED, BYTES,    pwm,              10)
#define HWIL_CALLBACK pb_default_field_callback
#define HWIL_DEFAULT NULL

extern const pb_msgdesc_t HWIL_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HWIL_fields &HWIL_msg

/* Maximum encoded size of messages (where known) */
/* HWIL_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
